/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

#define _CRT_SECURE_NO_WARNINGS 1
#include <stdio.h>

int main(void) {

	int initial = 0, num2 = 1, PreviousValue, sum = 0;

	while (initial < 4000000)
	{

		PreviousValue = initial + num2;
		PreviousValue += num2;

		if (PreviousValue % 2 == 0)
		{
			printf("\nEven-Valued Term: %d\n", PreviousValue);
			sum += PreviousValue;
		}

		initial++;
	}

	printf("\n\nThe sum of the Even-Valued terms are: %d\n\n", sum);


	return (0);
}